name: CI

on:
  push:
    branches: [ main, docker ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push to Dockerhub
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3.3.0
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gia:latest
      - name: Build Image on PR
        if: github.event_name != 'pull_request'
        uses: docker/build-push-action@v3.3.0
        with:
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/gia:latest
